### ISSUE TITLE
提示 multi ./node_modules/react-dev-utils/webpackHotDevClient.js ./src/index.tsx Module not found: Can't resolve '/Users/Mac/work/demo/src/features/food' in '/Users/Mac/work/demo'

### ISSUE THREAD

**Issue by qld-cf** [laomu1988/filter-ignore-loader#1]
Module not found: Can't resolve '/Users/Mac/work/demo/src/features/food' in '/Users/Mac/work/demo'

@laomu1988 

希望得到回复 谢谢

**Comment by laomu1024** [comment]
不了解具体项目配置，假如loader按原readme中配置是有问题的，将loader改为使用'filter-ignore-loader'试试

**Comment by qld-cf** [comment]
> 不了解具体项目配置，假如loader按原readme中配置是有问题的，将loader改为使用'filter-ignore-loader'试试
是这样配的
需要忽略的文件夹，外部其他地方还有和这个文件夹联系的，所以可能单单用插件无法解决了
tks anyway
